create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  email text not null unique,
  role text not null check (role in ('admin', 'interior_manager')),
  created_at timestamptz not null default now()
);

alter table public.user_roles enable row level security;

drop policy if exists "users read own role" on public.user_roles;
create policy "users read own role"
on public.user_roles
for select
using (lower(email) = lower(auth.jwt() ->> 'email'));

drop policy if exists "public read payments" on public.payments;
drop policy if exists "public insert payments" on public.payments;
drop policy if exists "public update pending payments" on public.payments;

create policy "authenticated read payments"
on public.payments
for select
using (auth.role() = 'authenticated');

create policy "authenticated insert payments"
on public.payments
for insert
with check (
  auth.role() = 'authenticated'
  and status = '신청'
  and amount > 0
  and length(trim(store)) > 0
  and length(trim(vendor)) > 0
);

create policy "authenticated update pending payments"
on public.payments
for update
using (auth.role() = 'authenticated' and status = '신청')
with check (auth.role() = 'authenticated' and status in ('승인', '반려'));

drop policy if exists "public read stores" on public.stores;
drop policy if exists "public insert stores" on public.stores;

create policy "authenticated read stores"
on public.stores
for select
using (auth.role() = 'authenticated');

create policy "authenticated insert stores"
on public.stores
for insert
with check (
  auth.role() = 'authenticated'
  and length(trim(name)) > 0
  and area > 0
  and budget > 0
  and spent >= 0
  and status in ('완료', '진행중', '미착공')
);

drop policy if exists "public read vendors" on public.vendors;
drop policy if exists "public insert vendors" on public.vendors;

create policy "authenticated read vendors"
on public.vendors
for select
using (auth.role() = 'authenticated');

create policy "authenticated insert vendors"
on public.vendors
for insert
with check (
  auth.role() = 'authenticated'
  and length(trim(name)) > 0
  and length(trim(category)) > 0
  and length(trim(bank)) > 0
  and length(trim(account_number)) > 0
  and length(trim(account_holder)) > 0
  and risk = '정상'
  and total = 0
);

drop policy if exists "public read construction cost parts" on public.construction_cost_parts;

create policy "authenticated read construction cost parts"
on public.construction_cost_parts
for select
using (auth.role() = 'authenticated');
