create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  store text not null,
  vendor text not null,
  payment_item text,
  estimate_total bigint,
  payment_type text not null default '일시 지급' check (payment_type in ('일시 지급', '선금 50%', '잔금 50%', '직접 입력')),
  amount bigint not null,
  vendor_bank text,
  vendor_account_number text,
  vendor_account_holder text,
  tax_type text not null default '일반 송금' check (tax_type in ('일반 송금', '사업소득 3.3%')),
  withholding_amount bigint not null default 0,
  net_amount bigint,
  attachment_files jsonb not null default '{}'::jsonb,
  estimate_group_mode text not null default '매장별 항목 합산',
  estimate_group_key text,
  memo text,
  status text not null check (status in ('승인', '신청', '반려')),
  requested_at date not null default current_date
);

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  region text,
  name text not null,
  fixture_count integer not null default 0,
  area integer not null,
  status text not null check (status in ('완료', '진행중', '미착공')),
  budget bigint not null,
  spent bigint not null default 0,
  document_required boolean not null default false,
  excel_row integer
);

create table if not exists public.construction_cost_parts (
  id bigint generated by default as identity primary key,
  store_name text not null,
  excel_row integer not null,
  part_name text not null,
  amount bigint not null default 0
);

create table if not exists public.store_quotes (
  id bigint generated by default as identity primary key,
  store_name text not null unique,
  quote_status text not null default '정산중' check (quote_status in ('정산중', '견적 확정', '계약 완료')),
  margin_rate numeric not null default 35,
  direct_cost bigint not null default 0,
  fixture_cost bigint not null default 0,
  cost_total bigint not null default 0,
  supply_amount bigint not null default 0,
  vat_amount bigint not null default 0,
  total_amount bigint not null default 0,
  quote_confirmed_at timestamptz,
  contract_completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.construction_starts (
  id bigint generated by default as identity primary key,
  store_name text not null,
  area integer not null,
  drawing_note text,
  drawing_files jsonb not null default '[]'::jsonb,
  wall_cabinet_count integer not null default 0,
  display_fixture_count integer not null default 0,
  counter_count integer not null default 0,
  fixture_count integer not null default 0,
  table_count integer not null default 0,
  sign_count integer not null default 0,
  base_photo_note text,
  base_photo_files jsonb not null default '[]'::jsonb,
  special_notes text,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'construction-start-files',
  'construction-start-files',
  true,
  20971520,
  null
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vendor-files',
  'vendor-files',
  true,
  20971520,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'payment-files',
  'payment-files',
  true,
  20971520,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  email text not null unique,
  role text not null check (role in ('admin', 'interior_manager')),
  created_at timestamptz not null default now()
);

create or replace function public.assign_default_interior_manager_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_roles (email, role)
  values (new.email, 'interior_manager')
  on conflict (email) do nothing;

  return new;
end;
$$;

drop trigger if exists assign_default_interior_manager_role on auth.users;
create trigger assign_default_interior_manager_role
after insert on auth.users
for each row
execute function public.assign_default_interior_manager_role();

create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  bank text not null,
  account_number text,
  account_holder text,
  attachment_files jsonb not null default '{}'::jsonb,
  risk text not null default '정상',
  total bigint not null default 0
);

alter table public.payments enable row level security;
alter table public.stores enable row level security;
alter table public.vendors enable row level security;
alter table public.construction_cost_parts enable row level security;
alter table public.store_quotes enable row level security;
alter table public.construction_starts enable row level security;
alter table public.user_roles enable row level security;

create policy "authenticated read payments" on public.payments for select using (auth.role() = 'authenticated');
create policy "authenticated read stores" on public.stores for select using (auth.role() = 'authenticated');
create policy "authenticated read vendors" on public.vendors for select using (auth.role() = 'authenticated');
create policy "authenticated read construction cost parts" on public.construction_cost_parts for select using (auth.role() = 'authenticated');
create policy "authenticated read store quotes" on public.store_quotes for select using (auth.role() = 'authenticated');
create policy "authenticated read construction starts" on public.construction_starts for select using (auth.role() = 'authenticated');
create policy "users read own role" on public.user_roles for select using (lower(email) = lower(auth.jwt() ->> 'email'));
create policy user_roles_read_authenticated on public.user_roles for select using (auth.role() = 'authenticated');

create policy construction_files_read
on storage.objects
for select
using (bucket_id = 'construction-start-files' and auth.role() = 'authenticated');

create policy construction_files_insert
on storage.objects
for insert
with check (bucket_id = 'construction-start-files' and auth.role() = 'authenticated');

create policy payment_files_read
on storage.objects
for select
using (bucket_id = 'payment-files' and auth.role() = 'authenticated');

create policy payment_files_insert
on storage.objects
for insert
with check (bucket_id = 'payment-files' and auth.role() = 'authenticated');

create policy vendor_files_read
on storage.objects
for select
using (bucket_id = 'vendor-files' and auth.role() = 'authenticated');

create policy vendor_files_insert
on storage.objects
for insert
with check (bucket_id = 'vendor-files' and auth.role() = 'authenticated');

create policy "authenticated insert stores"
on public.stores
for insert
with check (
  auth.role() = 'authenticated'
  and length(trim(name)) > 0
  and area > 0
  and budget > 0
  and spent >= 0
  and status in ('완료', '진행중', '미착공')
);

create policy "authenticated insert vendors"
on public.vendors
for insert
with check (
  auth.role() = 'authenticated'
  and length(trim(name)) > 0
  and length(trim(category)) > 0
  and length(trim(bank)) > 0
  and length(trim(account_number)) > 0
  and length(trim(account_holder)) > 0
  and risk = '정상'
  and total = 0
);

create policy "authenticated insert payments"
on public.payments
for insert
with check (
  auth.role() = 'authenticated'
  and status = '신청'
  and amount > 0
  and estimate_total > 0
  and withholding_amount >= 0
  and net_amount > 0
  and length(trim(store)) > 0
  and length(trim(vendor)) > 0
  and length(trim(vendor_bank)) > 0
  and length(trim(vendor_account_number)) > 0
  and length(trim(vendor_account_holder)) > 0
  and length(trim(payment_item)) > 0
  and payment_type in ('일시 지급', '선금 50%', '잔금 50%', '직접 입력')
  and tax_type in ('일반 송금', '사업소득 3.3%')
  and length(trim(estimate_group_key)) > 0
);

create policy "authenticated insert construction starts"
on public.construction_starts
for insert
with check (
  auth.role() = 'authenticated'
  and length(trim(store_name)) > 0
  and area > 0
  and wall_cabinet_count >= 0
  and display_fixture_count >= 0
  and counter_count >= 0
  and fixture_count >= 0
  and table_count >= 0
  and sign_count >= 0
);

create policy "authenticated upsert store quotes"
on public.store_quotes
for insert
with check (
  auth.role() = 'authenticated'
  and length(trim(store_name)) > 0
  and quote_status in ('정산중', '견적 확정', '계약 완료')
  and margin_rate >= 0
  and cost_total >= 0
  and supply_amount >= 0
  and vat_amount >= 0
  and total_amount >= 0
);

create policy "authenticated update store quotes"
on public.store_quotes
for update
using (auth.role() = 'authenticated')
with check (
  auth.role() = 'authenticated'
  and length(trim(store_name)) > 0
  and quote_status in ('정산중', '견적 확정', '계약 완료')
  and margin_rate >= 0
  and cost_total >= 0
  and supply_amount >= 0
  and vat_amount >= 0
  and total_amount >= 0
);

create policy "authenticated update pending payments"
on public.payments
for update
using (auth.role() = 'authenticated' and status = '신청')
with check (auth.role() = 'authenticated' and status in ('승인', '반려'));

create policy authenticated_update_vendors
on public.vendors
for update
using (auth.role() = 'authenticated')
with check (
  auth.role() = 'authenticated'
  and length(trim(name)) > 0
  and length(trim(category)) > 0
  and length(trim(bank)) > 0
  and length(trim(account_number)) > 0
  and length(trim(account_holder)) > 0
);

insert into public.stores (name, area, status, budget, spent) values
  ('성수 플래그십', 52, '완료', 210000000, 198400000),
  ('부산 센텀', 47, '진행중', 186000000, 122700000),
  ('대전 둔산', 39, '진행중', 144000000, 88200000),
  ('제주 노형', 42, '미착공', 158000000, 0)
on conflict do nothing;

insert into public.vendors (name, category, bank, risk, total) values
  ('도원인테리어', '시공', '신한은행', '정상', 124500000),
  ('한빛전기', '전기', '국민은행', '정상', 73800000),
  ('서진설비', '설비', '하나은행', '증빙확인', 41200000)
on conflict do nothing;
