create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  store text not null,
  vendor text not null,
  amount bigint not null,
  status text not null check (status in ('승인', '신청', '반려')),
  requested_at date not null default current_date
);

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  name text not null,
  area integer not null,
  status text not null check (status in ('완료', '진행중', '미착공')),
  budget bigint not null,
  spent bigint not null default 0
);

create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  bank text not null,
  risk text not null default '정상',
  total bigint not null default 0
);

alter table public.payments enable row level security;
alter table public.stores enable row level security;
alter table public.vendors enable row level security;

create policy "public read payments" on public.payments for select using (true);
create policy "public read stores" on public.stores for select using (true);
create policy "public read vendors" on public.vendors for select using (true);

drop policy if exists "public insert payments" on public.payments;
create policy "public insert payments"
on public.payments
for insert
with check (
  status = '신청'
  and amount > 0
  and length(trim(store)) > 0
  and length(trim(vendor)) > 0
);

insert into public.payments (store, vendor, amount, status, requested_at) values
  ('성수 플래그십', '한빛전기', 18400000, '승인', '2026-05-28'),
  ('부산 센텀', '도원인테리어', 32700000, '신청', '2026-05-27'),
  ('대전 둔산', '서진설비', 9800000, '반려', '2026-05-26'),
  ('제주 노형', '제이건축', 24100000, '승인', '2026-05-25')
on conflict do nothing;

insert into public.stores (name, area, status, budget, spent) values
  ('성수 플래그십', 52, '완료', 210000000, 198400000),
  ('부산 센텀', 47, '진행중', 186000000, 122700000),
  ('대전 둔산', 39, '진행중', 144000000, 88200000),
  ('제주 노형', 42, '미착공', 158000000, 0)
on conflict do nothing;

insert into public.vendors (name, category, bank, risk, total) values
  ('도원인테리어', '시공', '신한은행', '정상', 124500000),
  ('한빛전기', '전기', '국민은행', '정상', 73800000),
  ('서진설비', '설비', '하나은행', '증빙확인', 41200000)
on conflict do nothing;
