create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  store text not null,
  vendor text not null,
  amount bigint not null,
  status text not null check (status in ('승인', '신청', '반려')),
  requested_at date not null default current_date
);

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  region text,
  name text not null,
  fixture_count integer not null default 0,
  area integer not null,
  status text not null check (status in ('완료', '진행중', '미착공')),
  budget bigint not null,
  spent bigint not null default 0,
  document_required boolean not null default false,
  excel_row integer
);

create table if not exists public.construction_cost_parts (
  id bigint generated by default as identity primary key,
  store_name text not null,
  excel_row integer not null,
  part_name text not null,
  amount bigint not null default 0
);

create table if not exists public.construction_starts (
  id bigint generated by default as identity primary key,
  store_name text not null,
  area integer not null,
  drawing_note text,
  drawing_files jsonb not null default '[]'::jsonb,
  fixture_count integer not null default 0,
  table_count integer not null default 0,
  sign_count integer not null default 0,
  base_photo_note text,
  base_photo_files jsonb not null default '[]'::jsonb,
  special_notes text,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'construction-start-files',
  'construction-start-files',
  true,
  20971520,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  email text not null unique,
  role text not null check (role in ('admin', 'interior_manager')),
  created_at timestamptz not null default now()
);

create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  bank text not null,
  account_number text,
  account_holder text,
  risk text not null default '정상',
  total bigint not null default 0
);

alter table public.payments enable row level security;
alter table public.stores enable row level security;
alter table public.vendors enable row level security;
alter table public.construction_cost_parts enable row level security;
alter table public.construction_starts enable row level security;
alter table public.user_roles enable row level security;

create policy "authenticated read payments" on public.payments for select using (auth.role() = 'authenticated');
create policy "authenticated read stores" on public.stores for select using (auth.role() = 'authenticated');
create policy "authenticated read vendors" on public.vendors for select using (auth.role() = 'authenticated');
create policy "authenticated read construction cost parts" on public.construction_cost_parts for select using (auth.role() = 'authenticated');
create policy "authenticated read construction starts" on public.construction_starts for select using (auth.role() = 'authenticated');
create policy "users read own role" on public.user_roles for select using (lower(email) = lower(auth.jwt() ->> 'email'));

create policy construction_files_read
on storage.objects
for select
using (bucket_id = 'construction-start-files' and auth.role() = 'authenticated');

create policy construction_files_insert
on storage.objects
for insert
with check (bucket_id = 'construction-start-files' and auth.role() = 'authenticated');

create policy "authenticated insert stores"
on public.stores
for insert
with check (
  auth.role() = 'authenticated'
  and length(trim(name)) > 0
  and area > 0
  and budget > 0
  and spent >= 0
  and status in ('완료', '진행중', '미착공')
);

create policy "authenticated insert vendors"
on public.vendors
for insert
with check (
  auth.role() = 'authenticated'
  and length(trim(name)) > 0
  and length(trim(category)) > 0
  and length(trim(bank)) > 0
  and length(trim(account_number)) > 0
  and length(trim(account_holder)) > 0
  and risk = '정상'
  and total = 0
);

create policy "authenticated insert payments"
on public.payments
for insert
with check (
  auth.role() = 'authenticated'
  and status = '신청'
  and amount > 0
  and length(trim(store)) > 0
  and length(trim(vendor)) > 0
);

create policy "authenticated insert construction starts"
on public.construction_starts
for insert
with check (
  auth.role() = 'authenticated'
  and length(trim(store_name)) > 0
  and area > 0
  and fixture_count >= 0
  and table_count >= 0
  and sign_count >= 0
);

create policy "authenticated update pending payments"
on public.payments
for update
using (auth.role() = 'authenticated' and status = '신청')
with check (auth.role() = 'authenticated' and status in ('승인', '반려'));

insert into public.payments (store, vendor, amount, status, requested_at) values
  ('성수 플래그십', '한빛전기', 18400000, '승인', '2026-05-28'),
  ('부산 센텀', '도원인테리어', 32700000, '신청', '2026-05-27'),
  ('대전 둔산', '서진설비', 9800000, '반려', '2026-05-26'),
  ('제주 노형', '제이건축', 24100000, '승인', '2026-05-25')
on conflict do nothing;

insert into public.stores (name, area, status, budget, spent) values
  ('성수 플래그십', 52, '완료', 210000000, 198400000),
  ('부산 센텀', 47, '진행중', 186000000, 122700000),
  ('대전 둔산', 39, '진행중', 144000000, 88200000),
  ('제주 노형', 42, '미착공', 158000000, 0)
on conflict do nothing;

insert into public.vendors (name, category, bank, risk, total) values
  ('도원인테리어', '시공', '신한은행', '정상', 124500000),
  ('한빛전기', '전기', '국민은행', '정상', 73800000),
  ('서진설비', '설비', '하나은행', '증빙확인', 41200000)
on conflict do nothing;
